<?php
 
$SEPARATOR = "/";
$PROJECT_BASE = $SEPARATOR."yaupa".$SEPARATOR;
$TEMPLATES_DIR = $PROJECT_BASE."templates".$SEPARATOR;
$STATIC_DIR = $PROJECT_BASE."static".$SEPARATOR;

$URL_CHARTER = $SEPARATOR.$_SERVER['DOCUMENT_ROOT'].$SEPARATOR.$PROJECT_BASE.$SEPARATOR."charter".$SEPARATOR;

 
?>